language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.0
notifications:
  email: false
gemfile: .gemfile
